### ISSUE TITLE
reroute build failure with ghc 8.4

### ISSUE THREAD

**Issue by DanBurton** [agrafix/Spock#140]
Add semigroup instances.
See also: https://ghc.haskell.org/trac/ghc/wiki/Migration/8.4#SemigroupMonoidsuperclasses

```
Building library for reroute-0.4.1.0..
[1 of 4] Compiling Data.PolyMap     ( src/Data/PolyMap.hs, dist/build/Data/PolyMap.o )

src/Data/PolyMap.hs:34:10: error:
    • Could not deduce (Semigroup (PolyMap c f a))
        arising from the superclasses of an instance declaration
      from the context: Alternative f
        bound by the instance declaration at src/Data/PolyMap.hs:34:10-48
    • In the instance declaration for ‘Monoid (PolyMap c f a)’
   |
34 | instance Alternative f => Monoid (PolyMap c f a) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by hibou107** [comment]
src\Data\PolyMap.hs:34:10: error:
    * Could not deduce (Semigroup (PolyMap c f a))

**Comment by Zialus** [comment]
@DanBurton 

Spock-0.13.0.0 and reroute 0.5.0.0 are working fine with ghc 8.4.3
