### ISSUE TITLE
Broken package < 0.11.0?

### ISSUE THREAD

**Issue by elfeck** [agrafix/Spock#90]
Heyoh,
thanks for your work on Spock and the 0.11 release. I want to transition soon but I need to be able to build the < 0.11 for the moment.  
Right now cabal gives me this error (ghc 8.01, cabal 1.24.0):
```
Preprocessing library Spock-0.10.0.1...
[ 1 of 13] Compiling Web.Spock.Internal.Wire ( src/Web/Spock/Internal/Wire.hs, dist/dist-sandbox-c1786a3c/build/Web/Spock/Internal/Wire.o )

src/Web/Spock/Internal/Wire.hs:43:1: error:
    Failed to load interface for ‘Web.Routing.AbstractRouter’
    Use -v to see a list of the files searched for.
cabal: Leaving directory '/tmp/cabal-tmp-8652/Spock-0.10.0.1'
```
Any ideas what causes this? A quick google search did not bring up anything really.

**Comment by agrafix** [comment]
Ah, this is very likely due to missing upper bounds. I've added them so it should work again now

**Comment by elfeck** [comment]
Yes, works now, thank you for the quick solution!
