### ISSUE TITLE
fails to build with ghc-9.6 stackage nightly

### ISSUE THREAD

**Issue by juhp** [agrafix/Spock#184]
```
       Building library for Spock-core-0.14.0.1..
       [8 of 8] Compiling Web.Spock.Core
       
       /var/stackage/work/unpack-dir/unpacked/Spock-core-0.14.0.1-2d79055a51d5bb2364ac70e29c033f981b11619d5e8fd2ec1a650ffedb07ecc3/src/Web/Spock/Core.hs:117:15: error: [GHC-88464]
           Variable not in scope:
             forM_
               :: [SpockMethod]
                  -> (reqTypes1
                      -> AR.RegistryT (ActionCtxT () m) () middleware1 reqTypes1 m1 ())
                  -> AR.RegistryT
                       (ActionT m)
                       ()
                       Wai.Middleware
                       SpockMethod
                       (ReaderT (LiftHooked ctx m) m)
                       a1
           |
       117 |               forM_ allStdMethods $ \mReg ->
           |               ^^^^^
       
       /var/stackage/work/unpack-dir/unpacked/Spock-core-0.14.0.1-2d79055a51d5bb2364ac70e29c033f981b11619d5e8fd2ec1a650ffedb07ecc3/src/Web/Spock/Core.hs:149:13: error: [GHC-88464]
           Variable not in scope:
             forM_
               :: [SpockMethod]
                  -> (reqTypes0 -> AR.RegistryT n0 b0 middleware0 reqTypes0 m0 ())
                  -> AR.RegistryT
                       (ActionT m)
                       ()
                       Wai.Middleware
                       SpockMethod
                       (ReaderT (LiftHooked ctx m) m)
                       a0
           |
       149 |             forM_ allStdMethods $ \mReg ->
           |             ^^^^^
```

**Comment by soupi** [comment]
https://github.com/agrafix/Spock/pull/185

**Comment by agrafix** [comment]
Fixed by merged PR #185 ([d0b51fa](https://github.com/agrafix/Spock/commit/d0b51fa60a83bfa5c1b5fc8fced18001e7321701)), which explicitly imports `forM_` from `Data.Foldable`. The fix is present on `master`; the current native packages build and all 140 tests pass with Cabal and Stack on GHC 9.14.1.

Closing as fixed in source. Publication of `Spock-core 0.14.1.0` to Hackage is still pending.
